# -*- coding: utf-8 -*-
"""BuzzBazz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tdwmBg0iLv3o2JWV9nsQDGRvJ1muihyW
"""

def print_numbers():
  x = 0 
  while x <= 100:
    if x % 2 == 0 and x % 5 == 0:
      print ( x , "buzz bazz NUMERO PAR Y MULTIPLO DE 5") 
    elif x % 2 == 0:
      print ( x , "buzz") 
    elif x % 5 == 0:
      print ( x , "bazz")
    else: 
      print(x)
    x += 1
    
print_numbers()