# -*- coding: utf-8 -*-
"""pokemon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WHjXYBtFxVaZ1APQlUY64IWJlJrMe0p
"""

from collections import defaultdict

def secuencia_palabras_pokemon(datos):
    letra_inicial = datos[0][0]
    p = diccionario[letra_inicial] -set(datos)
    if not p:
      return datos
    else:
        return max( (secuencia_palabras_pokemon([i]+ datos) for i in p), key=len)


palabras = '''audino bagon baltoy banette bidoof braviary bronzor carracosta charmeleon
cresselia croagunk darmanitan deino emboar emolga exeggcute gabite
girafarig gulpin haxorus heatmor heatran ivysaur jellicent jumpluff kangaskhan
kricketune landorus ledyba loudred lumineon lunatone machamp magnezone mamoswine
nosepass petilil pidgeotto pikachu pinsir poliwrath poochyena porygon2
porygonz registeel relicanth remoraid rufflet sableye scolipede scrafty seaking
sealeo silcoon simisear snivy snorlax spoink starly tirtouga trapinch treecko
tyrogue vigoroth vulpix wailord wartortle whismur wingull yamask'''.split()
diccionario = defaultdict(set)
for lista in palabras:
    diccionario[lista[-1]].add(lista)
tamaño = len((max( (secuencia_palabras_pokemon([lista]) for x in palabras), key=len)))
print (max( (secuencia_palabras_pokemon([lista]) for x in palabras), key=len))
print (tamaño)